version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: mysql_leantime
    restart: always
    environment:
      - MYSQL_DEBUG
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "${MYSQL_LEANTIME_HOST_PORT:-3306}:${MYSQL_LEANTIME_CONTAINER_PORT:-3306}"
    command: ${MYSQL_LEANTIME_COMMAND:-"--character-set-server=utf8 --collation-server=utf8_unicode_ci"}
  web:
    image: leantime/leantime:latest
    container_name: leantime
    environment:
      - LEAN_DB_HOST
      - LEAN_DB_USER
      - LEAN_DB_PASSWORD
      - LEAN_DB_DATABASE
    ports:
      - "${LEAN_SERVER_PROXY_HOST_PORT:-9000}:${LEAN_SERVER_PROXY_CONTAINER_PORT:-9000}"
      - "${LEAN_HTTP_HOST_PORT:-80}:${LEAN_HTTP_CONTAINER_PORT:-80}"
    depends_on:
      - db
